version: "2"
services:

  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql:cached
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ..:/var/www/html:delegated
      - ~/.ssh:/root/.ssh
      - ~/.composer/auth.json:/root/.composer/auth.json
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - backend

  myapp.dev:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=myapp.dev
      - NGINX_PORT=80
    networks:
      - backend
    command: /bin/bash -c "envsubst <  /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  backend:
    driver: bridge